import random
import subprocess
import sys

#  as generated by the generator, all in degrees
generation_long_range = 10
generation_lat_range = 10
generation_min_long = 30
generation_min_lat = 30

seeder_url = 'localhost:7003'


def main():
    total_entities = sys.argv[1]
    client_index = sys.argv[2]
    seed_entities_amount = sys.argv[3]

    run_trigger(total_entities, client_index, seed_entities_amount)
    #  run client


def run_trigger(total_entities, client_index, seed_entities_amount):
    # compute client's area of interest size
    entity_density = total_entities / (generation_long_range * generation_lat_range)  # generator dimensions
    area_lat_size = 1  # degrees
    area_long_size = 100 / (entity_density * area_lat_size)  # ensure 100 entities on average

    area_min_lat = random.uniform(30, 40 - area_lat_size)
    area_min_long = random.uniform(30, 40 - area_long_size)
    area_max_lat = area_min_lat + area_lat_size
    area_max_long = area_min_long + area_long_size

    subprocess.call(['python', 'trigger.py', seeder_url, seed_entities_amount,
                     area_min_long, area_max_long, area_min_lat, area_max_lat])


if __name__ == "__main__":
    main()
